server:
  host: "0.0.0.0"
  port: 8080

model:
  provider: "ollama"                  # "ollama" | "openai"
  model_name: "deepseek-coder"
  api_base: "http://ollama:11434"
  api_key_env: "OPENAI_API_KEY"       # used only if provider=openai

opensearch:
  scheme: "http"
  host: "opensearch"
  port: 9200
  username: null
  password: null
  index_runs: "cybrty-runs"
  index_actions: "cybrty-actions"
  index_planner: "cybrty-planner"

tools:
  binaries:
    nmap: "nmap"
    amass: "amass"
    nuclei: "nuclei"
    sqlmap: "sqlmap"
    hydra: "hydra"
    cme: "crackmapexec"
    nikto: "nikto"
  zap_api: "http://zap:8080"              # optional service; fall back to CLI if not present
  metasploit_rpc:
    host: "msfrpcd"
    port: 55552
    user: "msf"
    pass_env: "MSF_RPC_PASSWORD"

policy:
  allow_networks: ["10.0.0.0/8","192.168.0.0/16","127.0.0.0/8"]
  max_host_count: 4096
  exploit_simulation: false               # true allows real exploit (only if simulate=true per-run)

artifacts:
  dir: "./artifacts"
