artifacts:
  dir: ./artifacts
model:
  api_base: http://ollama:11434
  api_key_env: OPENAI_API_KEY
  model_name: deepseek-coder
  provider: ollama
opensearch:
  host: cybrty-dev-ca.wonderfuldune-e921120d.eastus.azurecontainerapps.io
  index_actions: cybrty-actions
  index_planner: cybrty-planner
  index_runs: cybrty-runs
  password: null
  port: 443
  scheme: https
  username: null
  path: /es/
  dashboard_url: https://cybrty-dev-ca.wonderfuldune-e921120d.eastus.azurecontainerapps.io
policy:
  allow_networks:
  - 10.0.0.0/8
  - 192.168.0.0/16
  - 127.0.0.0/8
  exploit_simulation: false
  max_host_count: 4096
server:
  host: 0.0.0.0
  port: 8080
tools:
  binaries:
    amass: amass
    cme: crackmapexec
    hydra: hydra
    nikto: nikto
    nmap: nmap
    nuclei: nuclei
    sqlmap: sqlmap
  metasploit_rpc:
    host: msfrpcd
    pass_env: MSF_RPC_PASSWORD
    port: 55525
    user: msf
  zap_api: http://zap:8080
